### ISSUE TITLE
appendStream is not really appending streams

### ISSUE THREAD

**Issue by mateenQureshi** [muaz-khan/MultiStreamsMixer#1]
I have one local video and one remote video, both are captured on different times. When local video is captured, i initialize the mixer with local video stream, when remote stream arrives, i am appending the remote stream in initialized mixer.  But when i preview the stream with mixer.getMixedStream() , it returns only first stream which was added while initialization

Looking forward for solution

**Comment by pspburner** [comment]
Suppose arrayOfMediaStreams is not really updated after concat() in method appendStreams.

```
this.appendStreams = function(streams) = {
  ...
  arrayOfMediaStreams.concat(streams);
  ...
}
```

**Comment by omarfr** [comment]
Hello @mateenQureshi  is this resolved ? 
@muaz-khan how can fix it ? i want to append other audio stream  during record.

**Comment by dinceremre** [comment]
any progress with this?
