### ISSUE TITLE
Import MultiStreamsMixer Javascript file with dependency instead of script

### ISSUE THREAD

**Issue by luanraithz** [muaz-khan/MultiStreamsMixer#7]
Is there way way of doing the following in a javascript file?
```javascript
import MultiStreamsMixer from 'multistreamsmixer'
// or even: 
import { MultiStreamsMixer } from 'multistreamsmixer'
```
It worked importing the script in the with a `script` tag, but we are trying to avoid this kind of approach (put things in the window).
I see that your [MultStreamsMixer.ts file](https://github.com/muaz-khan/MultiStreamsMixer/blob/master/MultiStreamsMixer.ts) exports the class, are there any reason to don't do so at the js file?

**Comment by luanraithz** [comment]
Sadly the way it worked was download MultiStreamsMixer.js file manually, and change it so it exports what I need, but I think it's a really bad approach.

**Comment by muaz-khan** [comment]
I'll add `import` and `require` in the next commit. Something like this:

```javascript
const MultiStreamsMixer = require('multistreamsmixer');
import { MultiStreamsMixer} from 'multistreamsmixer';
```

**Comment by luanraithz** [comment]
Ok, thanks a lot.

**Comment by muaz-khan** [comment]
Please install NPM package and test again. (`npm install multistreamsmixer`)

```javascript
import { MultiStreamsMixer} from 'multistreamsmixer';
```

**Comment by luanraithz** [comment]
Yeap it works now, thanks.
But you exported as:
` ``javascript 
 module.exports = MultiStreamsMixer;
```
So I have to import it as:
```javascript 
import MultiStreamsMixer from 'multistreamsmixer';
```
Do you intend to keep that way ? If so, the readme would have to be changed, I may change it and open a pull request if you don't want to bother with it.
